return {
	MaxIncrements = 10,
	augmentType = { -- TODO : Unify?
		"attackDamage",
		"attackSpeed",
		"aoe",
		"maxHealth",
		"lifeRegen",
		"damageReduction",
		"mobility",
		"luck",
		"increasedXp",
		"increasedPickupRange",
		"critChance",
		"critMultiplier",
	},
	["attackDamage"] = {
		Increment = 5,
		-- TODO :
		-- BaseCost = ,
		-- Cost Multiplier / Increment = ,
	},
	["attackSpeed"] = {
		Increment = 2,
	},
	["aoe"] = {
		Increment = 2,
	},
	["maxHealth"] = {
		Increment = 5,
	},
	["lifeRegen"] = {
		Increment = 1,
	},
	["damageReduction"] = {
		Increment = 2,
	},
	["mobility"] = {
		Increment = 0.5,
	},
	["luck"] = {
		Increment = 1,
	},
	["increasedXp"] = {
		Increment = 2,
	},
	["increasedPickupRange"] = {
		Increment = 2,
	},
	["critChance"] = {
		Increment = 2,
	},
	["critMultiplier"] = {
		Increment = 2,
	},
}
