return {
	["IronMace"] = {
		WeaponType = "Mace",
		BaseDamage = 30,
		AttackSpeed = 0.6,
		Range = 8,
	},
	["IronSword"] = {
		WeaponType = "Sword",
		BaseDamage = 20,
		AttackSpeed = 1,
		Range = 6,
	},
	["IronAxe"] = {
		WeaponType = "Axe",
		BaseDamage = 25,
		AttackSpeed = 0.8,
		Range = 8,
	},
	["WoodenClub"] = {
		WeaponType = "Mace",
		BaseDamage = 25,
		AttackSpeed = 0.7,
		Range = 8,
	},
}
